version: "3"
networks:
    default:
        driver: bridge
services:
    libpostal:
        image: pelias/libpostal-service
        container_name: pelias_libpostal
        user: ${DOCKER_USER}
        restart: always
        ports:
            - 4400:4400
    schema:
        image: pelias/schema:master
        container_name: pelias_schema
        user: ${DOCKER_USER}
        volumes:
            - ./pelias.json:/code/pelias.json
            - ./synonyms/custom_name.txt:/code/pelias/schema/synonyms/custom_name.txt
            - ./synonyms/custom_street.txt:/code/pelias/schema/synonyms/custom_street.txt
    api:
        image: pelias/api:master
        container_name: pelias_api
        user: ${DOCKER_USER}
        restart: always
        environment:
            - PORT=4000
        ports:
            - 4000:4000
        volumes:
            - ./pelias.json:/code/pelias.json
    
    csv-importer:
        image: pelias/csv-importer:master
        container_name: pelias_csv_importer
        user: ${DOCKER_USER}
        volumes:
            - ./pelias.json:/code/pelias.json
            - ${DATA_DIR}:/data
            - ./blacklist/:/data/blacklist
    transit:
        image: milesgrantibigroup/ibi-transit:v5
        container_name: pelias_transit
        user: ${DOCKER_USER}
        volumes:
            - ./pelias.json:/code/pelias.json
            - ${DATA_DIR}:/data
    elasticsearch:
        image: pelias/elasticsearch:7.5.1
        container_name: pelias_elasticsearch
        user: ${DOCKER_USER}
        restart: always
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            - ${DATA_DIR}/elasticsearch:/usr/share/elasticsearch/data
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
